=== 49694445/HeroesAutoBattler_client/config/schemas/mmaiSettings.json
{
    "type" : "object",
    "$schema" : "http://json-schema.org/draft-04/schema",
    "title" : "MMAI settings format",
    "description" : "Format used to define settings for the MMAI mod",
    "additionalProperties" : false,
    "required" : [ "models", "fallback", "temperature", "seed" ],
    "properties" : {
        "$comment" : {
            "type" : "array",
            "default" : [],
            "items" : {
                "type" : "string"
            }
        },
        "models" : {
            "type" : "object",
            "additionalProperties" : false,
            "required" : [ "attacker", "defender" ],
            "properties" : {
                "attacker" : { "type" : "string" },
                "defender" : { "type" : "string" }
            }
        },
        "fallback" : {
            "type" : "string",
            "default" : "BattleAI",
            "enum" : [ "BattleAI", "StupidAI" ]
        },
        "temperature" : {
            "type" : "number",
            "default" : 0.5
        },
        "maxPredictions" : {
            "type" : "integer",
            "minimum" : 1,
            "maximum" : 100000,
            "default" : 100
        },
        "seed" : {
            "type" : "number",
            "default" : 0
        }
    }
}

=== 49694445/HeroesAutoBattler_client/Mods/mmai/config/mmai-settings.json
{
  "$comment": [
    "Adjust temperature to alter model behaviour:",
    "  0.0 = greedy (deterministic)",
    "  1.0 = baseline",
    "  2.0 = uncertain",
    "  2.5 = dumb",
    "  3+ = garbage (too random)"
  ],
  "models": {
    "attacker": "attacker-nkjrmrsq-202509291846.onnx",
    "defender": "defender-tukbajrv-202509241418.onnx"
  },
  "fallback": "BattleAI",
  "temperature": 0.5,
  "maxPredictions": 1000,
  "seed": 0
}
